# n8n Standalone Launcher — generated by n8n-control.ps1
# Runs n8n in background with full environment from .env

$RootDir   = "c:\Users\saif_\Desktop\downs\Currently\Daily\Lectures\ANtiGrav\n8nlocal"
$N8nBin    = "$RootDir\node_modules\n8n\bin\n8n"
$EnvFile   = "$RootDir\.env"
$LogFile   = "$RootDir\logs\n8n-task.log"
$ErrFile   = "$RootDir\logs\n8n-task-error.log"
$PidFile   = "$RootDir\logs\n8n.pid"
$NodeExe   = (Get-Command node -ErrorAction Stop).Source

Set-Location $RootDir

# Load env vars from .env into the process environment
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith('#')) {
            $idx = $line.IndexOf('=')
            if ($idx -gt 0) {
                $key = $line.Substring(0, $idx).Trim()
                $val = $line.Substring($idx + 1).Trim().Trim('"').Trim("'")
                [System.Environment]::SetEnvironmentVariable($key, $val, 'Process')
            }
        }
    }
}

# Start n8n and redirect output to log files
$proc = Start-Process `
    -FilePath $NodeExe `
    -ArgumentList $N8nBin, "start" `
    -WorkingDirectory $RootDir `
    -NoNewWindow `
    -RedirectStandardOutput $LogFile `
    -RedirectStandardError $ErrFile `
    -PassThru

# Write PID to file for management
$proc.Id | Set-Content $PidFile
Write-Host "[n8n] Launched with PID $($proc.Id) on port 5679"

# Keep the launcher alive (Task Scheduler will not track child processes)
$proc.WaitForExit()
